---
title: "Time series global inflation rates"
author: "Brian"
date: "2024-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(readr)
library(ggplot2)
inflation <- read_csv("API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_84.csv")
ppp <- read.csv("Purchasing_power.csv")

```
```{r}
countries = data.frame(names=c("Mexico", "US", "Canada"))

ggplot(data=inflation, aes(x=Year)) +
  geom_line(aes(y=Canada, color="Canada"))+
  geom_line(aes(y=Mexico, color="Mexico"))+
  geom_line(aes(y=US, color="US")) + 
  labs(x="Year",y="Inflation %") +
  scale_colour_manual("", 
                      breaks = c("Canada", "Mexico", "US"),
                      values = c("darkred", "darkgreen", "darkblue")) +
  labs(title="Inflation Rate Percent Per Year")

#Scales two countries to the third to allow for comparisons
mex_scaled_ppp = ppp/ppp$Mexico
mex_scaled_ppp$Year = ppp$Year
can_scaled_ppp = ppp/ppp$Canada
can_scaled_ppp$Year = ppp$Year

#plots all of these scaled values to the inflation
ggplot(data=ppp, aes(x=Year)) +
  geom_line(aes(y=United.States, color="US")) + 
  geom_line(aes(y=Mexico, color="Mexico")) + 
  geom_line(aes(y=Canada, color="Canada")) + 
  labs(x="Year",y="Purchasing Power Parity") +
  scale_colour_manual("", 
                      breaks = c("Canada", "Mexico", "US"),
                      values = c("darkred", "darkgreen", "darkblue")) +
  labs(title="Purchasing Power Parity of Canada and Mexico Compared to the US")

ggplot(data=mex_scaled_ppp, aes(x=Year)) +
  geom_line(aes(y=United.States, color="US")) + 
  geom_line(aes(y=Mexico, color="Mexico")) + 
  geom_line(aes(y=Canada, color="Canada")) + 
  labs(x="Year",y="Purchasing Power Parity") +
  scale_colour_manual("", 
                      breaks = c("Canada", "Mexico", "US"),
                      values = c("darkred", "darkgreen", "darkblue")) +
  labs(title="Purchasing Power Parity of Canada and the US Compared to Mexico")

ggplot(data=can_scaled_ppp, aes(x=Year)) +
  geom_line(aes(y=United.States, color="US")) + 
  geom_line(aes(y=Mexico, color="Mexico")) + 
  geom_line(aes(y=Canada, color="Canada")) + 
  labs(x="Year",y="Purchasing Power Parity") +
  scale_colour_manual("", 
                      breaks = c("Canada", "Mexico", "US"),
                      values = c("darkred", "darkgreen", "darkblue")) +
  labs(title="Purchasing Power Parity of Mexico and the US Compared to Canada")

```
```{r}
#Conducts Granger test to determine correlation
library(lmtest)
ppp_on_inflation = matrix(c(0.0), ncol=3, nrow=3, byrow=TRUE)
 
colnames(ppp_on_inflation) = c('US','Canada','Mexico')
rownames(ppp_on_inflation) <- c('US','Canada','Mexico')

inflation_on_ppp = matrix(c(0.0), ncol=3, nrow=3, byrow=TRUE)
 
colnames(inflation_on_ppp) = c('US','Canada','Mexico')
rownames(inflation_on_ppp) <- c('US','Canada','Mexico')

#Canada and Mexico Scaled to the US PPP
ppp_on_inflation[3,1] <- grangertest(ppp$Mexico, inflation$Mexico)$Pr[2]
inflation_on_ppp[3,1] <- grangertest(inflation$Mexico, ppp$Mexico)$Pr[2]

ppp_on_inflation[2,1] <- grangertest(ppp$Canada, inflation$Canada)$Pr[2]
inflation_on_ppp[2,1] <- grangertest(inflation$Canada, ppp$Canada)$Pr[2]

#US and Canada scaled to the Mexico PPP
ppp_on_inflation[1,3] <- grangertest(mex_scaled_ppp$United.States, inflation$US)$Pr[2]
inflation_on_ppp[1,3] <- grangertest(inflation$US, mex_scaled_ppp$United.States)$Pr[2]

ppp_on_inflation[2,3] <- grangertest(mex_scaled_ppp$Canada, inflation$Canada)$Pr[2]
inflation_on_ppp[2,3] <- grangertest(inflation$Canada, mex_scaled_ppp$Canada)$Pr[2]

#US and Mexico scaled to Canada PPP
ppp_on_inflation[1,2] <- grangertest(can_scaled_ppp$United.States, inflation$US)$Pr[2]
inflation_on_ppp[1,2] <- grangertest(inflation$US, can_scaled_ppp$United.States)$Pr[2]

ppp_on_inflation[3,2] <- grangertest(can_scaled_ppp$Mexico, inflation$Mexico)$Pr[2]
inflation_on_ppp[3,2] <- grangertest(inflation$Mexico, can_scaled_ppp$Mexico)$Pr[2]

#Cleans up matrix
ppp_on_inflation[1,1] = '-'
ppp_on_inflation[2,2] = '-'
ppp_on_inflation[3,3] = '-'

inflation_on_ppp[1,1] = '-'
inflation_on_ppp[2,2] = '-'
inflation_on_ppp[3,3] = '-'
```

